# python -m exp.run \
#     --dataset=amazon_ratings \
#     --d=5 \
#     --num_bundles=1 \
#     --layers=5 \
#     --gnn_layers=5 \
#     --gnn_hidden=64 \
#     --pe_size=0 \
#     --hidden_channels=64 \
#     --epochs=2000 \
#     --early_stopping=200 \
#     --edge_weights=False \
#     --left_weights=False \
#     --right_weights=True \
#     --lr=0.02 \
#     --weight_decay=1e-7 \
#     --input_dropout=0.2 \
#     --dropout=0.2 \
#     --use_act=True \
#     --use_bias=True \
#     --folds=10 \
#     --model=CoopSheaf \
#     --normalised=True \
#     --orth='householder' \
#     --stop_strategy='acc' \
#     --entity="${ENTITY}"

python -m exp.run \
    --dataset=amazon_ratings \
    --d=4 \
    --num_bundles=1 \
    --layers=3 \
    --gnn_layers=2 \
    --gnn_hidden=32 \
    --pe_size=0 \
    --hidden_channels=64 \
    --epochs=2000 \
    --early_stopping=200 \
    --edge_weights=False \
    --left_weights=True \
    --right_weights=True \
    --lr=0.02 \
    --weight_decay=1e-7 \
    --input_dropout=0.2 \
    --dropout=0.2 \
    --use_act=True \
    --use_bias=True \
    --folds=10 \
    --model=CoopSheaf \
    --normalised=True \
    --orth='householder' \
    --stop_strategy='acc' \
    --entity="${ENTITY}"